# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Fri Feb 14 22:09:42 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName(_fromUtf8("TabWidget"))
        TabWidget.resize(590, 436)
        TabWidget.setStyleSheet(_fromUtf8("#tab,#tab_2 {\n"
"    background-color: rgb(163, 163, 163);\n"
"    \n"
"}\n"
"\n"
"#frame {\n"
"border: 3px solid gray;\n"
"border-radius: 40px;\n"
"background: white;\n"
"}\n"
"\n"
" QTabBar::tab:selected {\n"
"\n"
" }"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(20, 20, 541, 351))
        self.frame.setStyleSheet(_fromUtf8("#frame {\n"
"background: QLinearGradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #eef, stop: 1 #ccf);\n"
"}"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.layoutWidget = QtGui.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 50, 504, 240))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 0, 0, 5, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.comboBox_2 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox_2, 0, 2, 1, 1)
        self.comboBox = QtGui.QComboBox(self.layoutWidget)
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.lineEdit_8 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.horizontalLayout_2.addWidget(self.lineEdit_8)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit.setInputMask(_fromUtf8(""))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox.setWrapping(False)
        self.doubleSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox.setSingleStep(1.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout.addWidget(self.doubleSpinBox, 1, 2, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout.addWidget(self.lineEdit_3, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 1, 4, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_4, 2, 3, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout.addWidget(self.lineEdit_6, 3, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_3, 1, 3, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout.addWidget(self.lineEdit_7, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.gridLayout.addWidget(self.doubleSpinBox_3, 3, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 4, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.gridLayout.addWidget(self.doubleSpinBox_2, 2, 2, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout.addWidget(self.checkBox_3, 3, 4, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout.addWidget(self.lineEdit_5, 1, 0, 1, 1)
        self.comboBox_5 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_5.setEditable(True)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_5, 3, 3, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout.addWidget(self.checkBox_2, 2, 4, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 1, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEdit_4 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout.addWidget(self.lineEdit_4)
        self.checkBox_4 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.horizontalLayout.addWidget(self.checkBox_4)
        self.gridLayout_4.addLayout(self.horizontalLayout, 4, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 3, 1, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.layoutWidget)
        self.pushButton.setStyleSheet(_fromUtf8("#pushButton {\n"
"color: white;\n"
"background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #88d, stop: 0.1 #99e, stop: 0.49 #77c, stop: 0.5 #66b, stop: 1 #77c);\n"
"border-width: 1px;\n"
"border-color: #339;\n"
"border-style: solid;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"font-size: 15px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"\n"
"#pushButton:pressed {\n"
"     background-color: QLinearGradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
" }\n"
"\n"
"#pushButton:released{\n"
"color: white;\n"
"background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #88d, stop: 0.1 #99e, stop: 0.49 #77c, stop: 0.5 #66b, stop: 1 #77c);\n"
"border-width: 1px;\n"
"border-color: #339;\n"
"border-style: solid;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"font-size: 15px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"\n"
"\n"
""))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_5.addWidget(self.pushButton, 1, 0, 1, 1)
        TabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tab_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 10, 531, 361))
        self.plainTextEdit.setStyleSheet(_fromUtf8("#plainTextEdit {\n"
"border: 3px solid gray;\n"
"border-radius: 20px;\n"
"background: white;\n"
"background: QLinearGradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FA8998, stop: 1 #FA324D);\n"
"}"))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        TabWidget.addTab(self.tab_2, _fromUtf8(""))

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        TabWidget.setWindowTitle(_translate("TabWidget", "TabWidget", None))
        self.comboBox_2.setItemText(0, _translate("TabWidget", "2014", None))
        self.comboBox_2.setItemText(1, _translate("TabWidget", "2013", None))
        self.comboBox_2.setItemText(2, _translate("TabWidget", "2012", None))
        self.comboBox_2.setItemText(3, _translate("TabWidget", "2011", None))
        self.comboBox_2.setItemText(4, _translate("TabWidget", "2010", None))
        self.comboBox_2.setItemText(5, _translate("TabWidget", "2009", None))
        self.comboBox_2.setItemText(6, _translate("TabWidget", "2008", None))
        self.comboBox_2.setItemText(7, _translate("TabWidget", "2007", None))
        self.comboBox_2.setItemText(8, _translate("TabWidget", "2006", None))
        self.comboBox_2.setItemText(9, _translate("TabWidget", "2005", None))
        self.comboBox_2.setItemText(10, _translate("TabWidget", "2004", None))
        self.comboBox_2.setItemText(11, _translate("TabWidget", "2003", None))
        self.comboBox_2.setItemText(12, _translate("TabWidget", "2002", None))
        self.comboBox_2.setItemText(13, _translate("TabWidget", "2001", None))
        self.comboBox_2.setItemText(14, _translate("TabWidget", "2000", None))
        self.comboBox_2.setItemText(15, _translate("TabWidget", "1999", None))
        self.comboBox_2.setItemText(16, _translate("TabWidget", "1998", None))
        self.comboBox_2.setItemText(17, _translate("TabWidget", "1997", None))
        self.comboBox_2.setItemText(18, _translate("TabWidget", "1996", None))
        self.comboBox_2.setItemText(19, _translate("TabWidget", "1995", None))
        self.comboBox_2.setItemText(20, _translate("TabWidget", "1994", None))
        self.comboBox_2.setItemText(21, _translate("TabWidget", "1993", None))
        self.comboBox_2.setItemText(22, _translate("TabWidget", "1992", None))
        self.comboBox_2.setItemText(23, _translate("TabWidget", "1991", None))
        self.comboBox_2.setItemText(24, _translate("TabWidget", "1990", None))
        self.comboBox.setCurrentText(_translate("TabWidget", "2014", None))
        self.comboBox.setItemText(0, _translate("TabWidget", "2014", None))
        self.comboBox.setItemText(1, _translate("TabWidget", "2013", None))
        self.comboBox.setItemText(2, _translate("TabWidget", "2012", None))
        self.comboBox.setItemText(3, _translate("TabWidget", "2011", None))
        self.comboBox.setItemText(4, _translate("TabWidget", "2010", None))
        self.comboBox.setItemText(5, _translate("TabWidget", "2009", None))
        self.comboBox.setItemText(6, _translate("TabWidget", "2008", None))
        self.comboBox.setItemText(7, _translate("TabWidget", "2007", None))
        self.comboBox.setItemText(8, _translate("TabWidget", "2006", None))
        self.comboBox.setItemText(9, _translate("TabWidget", "2005", None))
        self.comboBox.setItemText(10, _translate("TabWidget", "2004", None))
        self.comboBox.setItemText(11, _translate("TabWidget", "2003", None))
        self.comboBox.setItemText(12, _translate("TabWidget", "2002", None))
        self.comboBox.setItemText(13, _translate("TabWidget", "2001", None))
        self.comboBox.setItemText(14, _translate("TabWidget", "2000", None))
        self.comboBox.setItemText(15, _translate("TabWidget", "1999", None))
        self.comboBox.setItemText(16, _translate("TabWidget", "1998", None))
        self.comboBox.setItemText(17, _translate("TabWidget", "1997", None))
        self.comboBox.setItemText(18, _translate("TabWidget", "1996", None))
        self.comboBox.setItemText(19, _translate("TabWidget", "1995", None))
        self.comboBox.setItemText(20, _translate("TabWidget", "1994", None))
        self.comboBox.setItemText(21, _translate("TabWidget", "1993", None))
        self.comboBox.setItemText(22, _translate("TabWidget", "1992", None))
        self.comboBox.setItemText(23, _translate("TabWidget", "1991", None))
        self.comboBox.setItemText(24, _translate("TabWidget", "1990", None))
        self.label.setText(_translate("TabWidget", "Tímabil meðalverðbólgu: ", None))
        self.lineEdit_8.setPlaceholderText(_translate("TabWidget", "eða þín egin tala.", None))
        self.lineEdit.setPlaceholderText(_translate("TabWidget", "Sláðu inn lánaupphæð.", None))
        self.lineEdit_3.setPlaceholderText(_translate("TabWidget", "Sláðu inn lánaupphæð.", None))
        self.label_2.setText(_translate("TabWidget", "Vextir", None))
        self.checkBox.setText(_translate("TabWidget", "Verðtryggt", None))
        self.comboBox_4.setItemText(0, _translate("TabWidget", "1", None))
        self.comboBox_4.setItemText(1, _translate("TabWidget", "2", None))
        self.comboBox_4.setItemText(2, _translate("TabWidget", "3", None))
        self.comboBox_4.setItemText(3, _translate("TabWidget", "4", None))
        self.comboBox_4.setItemText(4, _translate("TabWidget", "5", None))
        self.comboBox_4.setItemText(5, _translate("TabWidget", "6", None))
        self.comboBox_4.setItemText(6, _translate("TabWidget", "7", None))
        self.comboBox_4.setItemText(7, _translate("TabWidget", "8", None))
        self.comboBox_4.setItemText(8, _translate("TabWidget", "9", None))
        self.comboBox_4.setItemText(9, _translate("TabWidget", "10", None))
        self.comboBox_4.setItemText(10, _translate("TabWidget", "11", None))
        self.comboBox_4.setItemText(11, _translate("TabWidget", "12", None))
        self.comboBox_4.setItemText(12, _translate("TabWidget", "13", None))
        self.comboBox_4.setItemText(13, _translate("TabWidget", "14", None))
        self.comboBox_4.setItemText(14, _translate("TabWidget", "15", None))
        self.comboBox_4.setItemText(15, _translate("TabWidget", "16", None))
        self.comboBox_4.setItemText(16, _translate("TabWidget", "17", None))
        self.comboBox_4.setItemText(17, _translate("TabWidget", "18", None))
        self.comboBox_4.setItemText(18, _translate("TabWidget", "19", None))
        self.comboBox_4.setItemText(19, _translate("TabWidget", "20", None))
        self.comboBox_4.setItemText(20, _translate("TabWidget", "21", None))
        self.comboBox_4.setItemText(21, _translate("TabWidget", "22", None))
        self.comboBox_4.setItemText(22, _translate("TabWidget", "23", None))
        self.comboBox_4.setItemText(23, _translate("TabWidget", "24", None))
        self.comboBox_4.setItemText(24, _translate("TabWidget", "25", None))
        self.comboBox_4.setItemText(25, _translate("TabWidget", "26", None))
        self.comboBox_4.setItemText(26, _translate("TabWidget", "27", None))
        self.comboBox_4.setItemText(27, _translate("TabWidget", "28", None))
        self.comboBox_4.setItemText(28, _translate("TabWidget", "29", None))
        self.comboBox_4.setItemText(29, _translate("TabWidget", "30", None))
        self.comboBox_4.setItemText(30, _translate("TabWidget", "31", None))
        self.comboBox_4.setItemText(31, _translate("TabWidget", "32", None))
        self.comboBox_4.setItemText(32, _translate("TabWidget", "33", None))
        self.comboBox_4.setItemText(33, _translate("TabWidget", "34", None))
        self.comboBox_4.setItemText(34, _translate("TabWidget", "35", None))
        self.comboBox_4.setItemText(35, _translate("TabWidget", "36", None))
        self.comboBox_4.setItemText(36, _translate("TabWidget", "37", None))
        self.comboBox_4.setItemText(37, _translate("TabWidget", "38", None))
        self.comboBox_4.setItemText(38, _translate("TabWidget", "39", None))
        self.comboBox_4.setItemText(39, _translate("TabWidget", "40", None))
        self.comboBox_4.setItemText(40, _translate("TabWidget", "41", None))
        self.comboBox_4.setItemText(41, _translate("TabWidget", "42", None))
        self.comboBox_4.setItemText(42, _translate("TabWidget", "43", None))
        self.comboBox_4.setItemText(43, _translate("TabWidget", "44", None))
        self.comboBox_4.setItemText(44, _translate("TabWidget", "45", None))
        self.comboBox_4.setItemText(45, _translate("TabWidget", "46", None))
        self.comboBox_4.setItemText(46, _translate("TabWidget", "47", None))
        self.comboBox_4.setItemText(47, _translate("TabWidget", "48", None))
        self.comboBox_4.setItemText(48, _translate("TabWidget", "49", None))
        self.comboBox_4.setItemText(49, _translate("TabWidget", "50", None))
        self.lineEdit_6.setPlaceholderText(_translate("TabWidget", "Sláðu inn nafn láns.", None))
        self.lineEdit_2.setPlaceholderText(_translate("TabWidget", "Sláðu inn lánaupphæð.", None))
        self.comboBox_3.setItemText(0, _translate("TabWidget", "1", None))
        self.comboBox_3.setItemText(1, _translate("TabWidget", "2", None))
        self.comboBox_3.setItemText(2, _translate("TabWidget", "3", None))
        self.comboBox_3.setItemText(3, _translate("TabWidget", "4", None))
        self.comboBox_3.setItemText(4, _translate("TabWidget", "5", None))
        self.comboBox_3.setItemText(5, _translate("TabWidget", "6", None))
        self.comboBox_3.setItemText(6, _translate("TabWidget", "7", None))
        self.comboBox_3.setItemText(7, _translate("TabWidget", "8", None))
        self.comboBox_3.setItemText(8, _translate("TabWidget", "9", None))
        self.comboBox_3.setItemText(9, _translate("TabWidget", "10", None))
        self.comboBox_3.setItemText(10, _translate("TabWidget", "11", None))
        self.comboBox_3.setItemText(11, _translate("TabWidget", "12", None))
        self.comboBox_3.setItemText(12, _translate("TabWidget", "13", None))
        self.comboBox_3.setItemText(13, _translate("TabWidget", "14", None))
        self.comboBox_3.setItemText(14, _translate("TabWidget", "15", None))
        self.comboBox_3.setItemText(15, _translate("TabWidget", "16", None))
        self.comboBox_3.setItemText(16, _translate("TabWidget", "17", None))
        self.comboBox_3.setItemText(17, _translate("TabWidget", "18", None))
        self.comboBox_3.setItemText(18, _translate("TabWidget", "19", None))
        self.comboBox_3.setItemText(19, _translate("TabWidget", "20", None))
        self.comboBox_3.setItemText(20, _translate("TabWidget", "21", None))
        self.comboBox_3.setItemText(21, _translate("TabWidget", "22", None))
        self.comboBox_3.setItemText(22, _translate("TabWidget", "23", None))
        self.comboBox_3.setItemText(23, _translate("TabWidget", "24", None))
        self.comboBox_3.setItemText(24, _translate("TabWidget", "25", None))
        self.comboBox_3.setItemText(25, _translate("TabWidget", "26", None))
        self.comboBox_3.setItemText(26, _translate("TabWidget", "27", None))
        self.comboBox_3.setItemText(27, _translate("TabWidget", "28", None))
        self.comboBox_3.setItemText(28, _translate("TabWidget", "29", None))
        self.comboBox_3.setItemText(29, _translate("TabWidget", "30", None))
        self.comboBox_3.setItemText(30, _translate("TabWidget", "31", None))
        self.comboBox_3.setItemText(31, _translate("TabWidget", "32", None))
        self.comboBox_3.setItemText(32, _translate("TabWidget", "33", None))
        self.comboBox_3.setItemText(33, _translate("TabWidget", "34", None))
        self.comboBox_3.setItemText(34, _translate("TabWidget", "35", None))
        self.comboBox_3.setItemText(35, _translate("TabWidget", "36", None))
        self.comboBox_3.setItemText(36, _translate("TabWidget", "37", None))
        self.comboBox_3.setItemText(37, _translate("TabWidget", "38", None))
        self.comboBox_3.setItemText(38, _translate("TabWidget", "39", None))
        self.comboBox_3.setItemText(39, _translate("TabWidget", "40", None))
        self.comboBox_3.setItemText(40, _translate("TabWidget", "41", None))
        self.comboBox_3.setItemText(41, _translate("TabWidget", "42", None))
        self.comboBox_3.setItemText(42, _translate("TabWidget", "43", None))
        self.comboBox_3.setItemText(43, _translate("TabWidget", "44", None))
        self.comboBox_3.setItemText(44, _translate("TabWidget", "45", None))
        self.comboBox_3.setItemText(45, _translate("TabWidget", "46", None))
        self.comboBox_3.setItemText(46, _translate("TabWidget", "47", None))
        self.comboBox_3.setItemText(47, _translate("TabWidget", "48", None))
        self.comboBox_3.setItemText(48, _translate("TabWidget", "49", None))
        self.comboBox_3.setItemText(49, _translate("TabWidget", "50", None))
        self.lineEdit_7.setPlaceholderText(_translate("TabWidget", "Sláðu inn nafn láns.", None))
        self.label_4.setText(_translate("TabWidget", "Höfuðstóll Láns", None))
        self.label_6.setText(_translate("TabWidget", "Verðtrygging", None))
        self.label_7.setText(_translate("TabWidget", "Lánstími, ár", None))
        self.label_5.setText(_translate("TabWidget", "Nafn Láns", None))
        self.checkBox_3.setText(_translate("TabWidget", "Verðtryggt", None))
        self.lineEdit_5.setPlaceholderText(_translate("TabWidget", "Sláðu inn nafn láns.", None))
        self.comboBox_5.setItemText(0, _translate("TabWidget", "1", None))
        self.comboBox_5.setItemText(1, _translate("TabWidget", "2", None))
        self.comboBox_5.setItemText(2, _translate("TabWidget", "3", None))
        self.comboBox_5.setItemText(3, _translate("TabWidget", "4", None))
        self.comboBox_5.setItemText(4, _translate("TabWidget", "5", None))
        self.comboBox_5.setItemText(5, _translate("TabWidget", "6", None))
        self.comboBox_5.setItemText(6, _translate("TabWidget", "7", None))
        self.comboBox_5.setItemText(7, _translate("TabWidget", "8", None))
        self.comboBox_5.setItemText(8, _translate("TabWidget", "9", None))
        self.comboBox_5.setItemText(9, _translate("TabWidget", "10", None))
        self.comboBox_5.setItemText(10, _translate("TabWidget", "11", None))
        self.comboBox_5.setItemText(11, _translate("TabWidget", "12", None))
        self.comboBox_5.setItemText(12, _translate("TabWidget", "13", None))
        self.comboBox_5.setItemText(13, _translate("TabWidget", "14", None))
        self.comboBox_5.setItemText(14, _translate("TabWidget", "15", None))
        self.comboBox_5.setItemText(15, _translate("TabWidget", "16", None))
        self.comboBox_5.setItemText(16, _translate("TabWidget", "17", None))
        self.comboBox_5.setItemText(17, _translate("TabWidget", "18", None))
        self.comboBox_5.setItemText(18, _translate("TabWidget", "19", None))
        self.comboBox_5.setItemText(19, _translate("TabWidget", "20", None))
        self.comboBox_5.setItemText(20, _translate("TabWidget", "21", None))
        self.comboBox_5.setItemText(21, _translate("TabWidget", "22", None))
        self.comboBox_5.setItemText(22, _translate("TabWidget", "23", None))
        self.comboBox_5.setItemText(23, _translate("TabWidget", "24", None))
        self.comboBox_5.setItemText(24, _translate("TabWidget", "25", None))
        self.comboBox_5.setItemText(25, _translate("TabWidget", "26", None))
        self.comboBox_5.setItemText(26, _translate("TabWidget", "27", None))
        self.comboBox_5.setItemText(27, _translate("TabWidget", "28", None))
        self.comboBox_5.setItemText(28, _translate("TabWidget", "29", None))
        self.comboBox_5.setItemText(29, _translate("TabWidget", "30", None))
        self.comboBox_5.setItemText(30, _translate("TabWidget", "31", None))
        self.comboBox_5.setItemText(31, _translate("TabWidget", "32", None))
        self.comboBox_5.setItemText(32, _translate("TabWidget", "33", None))
        self.comboBox_5.setItemText(33, _translate("TabWidget", "34", None))
        self.comboBox_5.setItemText(34, _translate("TabWidget", "35", None))
        self.comboBox_5.setItemText(35, _translate("TabWidget", "36", None))
        self.comboBox_5.setItemText(36, _translate("TabWidget", "37", None))
        self.comboBox_5.setItemText(37, _translate("TabWidget", "38", None))
        self.comboBox_5.setItemText(38, _translate("TabWidget", "39", None))
        self.comboBox_5.setItemText(39, _translate("TabWidget", "40", None))
        self.comboBox_5.setItemText(40, _translate("TabWidget", "41", None))
        self.comboBox_5.setItemText(41, _translate("TabWidget", "42", None))
        self.comboBox_5.setItemText(42, _translate("TabWidget", "43", None))
        self.comboBox_5.setItemText(43, _translate("TabWidget", "44", None))
        self.comboBox_5.setItemText(44, _translate("TabWidget", "45", None))
        self.comboBox_5.setItemText(45, _translate("TabWidget", "46", None))
        self.comboBox_5.setItemText(46, _translate("TabWidget", "47", None))
        self.comboBox_5.setItemText(47, _translate("TabWidget", "48", None))
        self.comboBox_5.setItemText(48, _translate("TabWidget", "49", None))
        self.comboBox_5.setItemText(49, _translate("TabWidget", "50", None))
        self.checkBox_2.setText(_translate("TabWidget", "Verðtryggt", None))
        self.lineEdit_4.setPlaceholderText(_translate("TabWidget", "Sláðu inn greiðslu.", None))
        self.checkBox_4.setText(_translate("TabWidget", "Mánaðarleg", None))
        self.pushButton.setText(_translate("TabWidget", "Reikna", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "Lán", None))
        self.plainTextEdit.setPlainText(_translate("TabWidget", "Hér birtist niðurstaðan þín.", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_2), _translate("TabWidget", "Niðurstaða", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TabWidget = QtGui.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())

